weights: .\runs\train\640x640-multi-scale=False-EXP2\weights\last.pt
cfg: ''
data: data/myDATA.yaml
hyp: data/hyps/hyp.scratch-high.yaml
epochs: 1000
batch_size: 40
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: true
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 4
project: runs/train
entity: null
name: 640x640-multi-scale=False-EXP
exist_ok: false
quad: false
linear_lr: true
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
patience: 300
save_dir: runs\train\640x640-multi-scale=False-EXP2
